name: ngrok-cimm
version: '2.3.5'
summary: Secure introspectable tunnels to localhost
description: |
  I want to expose a local server behind a NAT or firewall to the internet.
grade: stable
confinement: strict

apps:
  ngrok-cimm:
    command: ngrok
    plugs:
      - network-bind

parts:
  ngrok:
    source: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
    source-type: zip
    plugin: dump
    install: chmod 0755 ngrok
